spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/sfg_dev
    username: sfg_dev_user
    password: guru
    platform: mysql
#initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#We are aasking Hibernate to create the sql
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql